# Generated by Django 4.2.11 on 2025-04-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50, unique=True)),
                ('loading_port', models.CharField(max_length=100)),
                ('discharge_port', models.CharField(max_length=100)),
                ('ship_arrival_date', models.DateField()),
                ('ship_departure_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('bookings', models.ManyToManyField(related_name='vehicles', to='logistics.booking')),
            ],
        ),
    ]
