# Generated by Django 4.2.11 on 2025-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ship_arrival_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ship_departure_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
