# Generated by Django 4.2.11 on 2025-04-03 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_booking_ship_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ship_arrival_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ship_departure_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
