# Generated by Django 4.2.11 on 2025-04-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_booking_ship_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='logistics.booking'),
        ),
    ]
