# Generated by Django 4.2.11 on 2025-04-04 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_vehicle_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ship_arrival_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ship_departure_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='bookings',
            field=models.ManyToManyField(blank=True, null=True, related_name='vehicles', to='logistics.booking'),
        ),
    ]
