# Generated by Django 4.2.11 on 2025-04-06 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_alter_booking_ship_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='bookings',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.booking'),
        ),
    ]
