# Generated by Django 4.2.11 on 2025-04-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_vehicle_bookings_vehicle_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='booking',
            new_name='booking_id',
        ),
    ]
